WITH CTE AS (
	SELECT 
		DEPT_NBR AS DEPARTAMENTO,
		DEPT_NAME AS DEPARTAMENTO_NAME,
		CAT_NBR AS CATEGORIA,
		TRIBU,
		SQUAD,
		CATEGORY_NAME AS CATEGORIA_NAME,
		ROW_NUMBER() OVER (PARTITION BY DEPARTAMENTO, CATEGORIA ORDER BY SQUAD) AS R
	FROM WM_AD_HOC.TABLA_ASIGNACION
)

SELECT DISTINCT
	TRIBU,
	SQUAD,
	DEPARTAMENTO,
	DEPARTAMENTO_NAME,
	CATEGORIA,
	CATEGORIA_NAME
FROM CTE
WHERE R = 1
