/*
#'' Consulta que obtiene los precios futuros
#' 
#' Autor: Eduardo Castro <eduardo.castro0@walmart.com>
#' Colaboracion: 
#								Robert Paniagua <mrpania@walmart.com>
#'               Felipe Gerard <felipe.gerard@walmart.com>
#								Arturo Benitez <arturo.benitez@walmart.com>
#' 
*/

SELECT
	RB.ITEM_NBR,
	BF.FORMATO,
	AVG (RB.ITEM_RETAIL_AMT) AS precio_fut,
	AVG (RB.CUST_RETAIL_AMT) AS precio_iva_fut

FROM 
(
	SELECT
		D.DEPT_NBR,
		D.ITEM_NBR,
		D.ITEM1_DESC,		

		E.STORE_NBR,
		
		A.CHANGE_EFF_DATE,
		A.CHANGE_EXP_DATE,
		A.ITEM_RETAIL_AMT,
		A.CUST_RETAIL_AMT,
		A.VNPK_COST_AMT,
		A.VENDOR_PACK_QTY,
		A.RULE_ID,

		B.ALPHA_PRC_EVENT_CD,

		C.TRAIT_NBR,
		C.LAST_GEN_DATE

	FROM
		MXPRICMG.ITEM_FUTURE_CHANGE	A,
		MXPRICMG.PRICING_EVENT_TYPE	B,
		MXRULES0.KEY_SELECTION_RULE	C,
		MXITEM.ITEM D,
		MXTRAITS.TRAIT_STORE E
	WHERE	
		A.RULE_ID = C.RULE_ID
		AND	A.PRICING_EVENT_CD = B.PRICING_EVENT_CD
		AND	A.ITEM_NBR = D.ITEM_NBR
		AND C.TRAIT_NBR  = E.TRAIT_NBR
		AND A.CHANGE_EFF_DATE <= LAST_DAY(CURRENT_DATE + ?NUM_FUTMONTHS MONTH) -- EFF <= LAST
		AND A.CHANGE_EXP_DATE >= CASE WHEN ?NUM_FUTMONTHS = 0 THEN CURRENT_DATE ELSE LAST_DAY(CURRENT_DATE + ?NUM_FUTMONTHS MONTH - 1 MONTH) + 1 DAY END --EXP >= FIRST
		AND B.ALPHA_PRC_EVENT_CD IN ('AR','CA','CB','CP','OA','OB','OR','PA','SB','TR','VB')
		AND D.ITEM_TYPE_CODE IN (20,22,33,37,40,42)

	ORDER BY
	DEPT_NBR,ITEM_NBR,CHANGE_EFF_DATE
) AS RB

LEFT JOIN 
(
	SELECT
		STORE_NBR,
		CASE
		WHEN TRAIT_NBR IN (9) THEN 'BODEGA'
		WHEN TRAIT_NBR IN (1312) THEN 'MIBODEGA'
		WHEN TRAIT_NBR IN (969,136) THEN 'BAE'
		WHEN TRAIT_NBR IN (297) THEN 'SUPERCENTER'
		WHEN TRAIT_NBR IN (11) THEN 'SUPERAMA'
		ELSE 'OTRO' END AS FORMATO
	FROM
		MXTRAITS.TRAIT_STORE

	WHERE
		TRAIT_NBR IN (9,11,297,969,1312,136)
) AS BF ON (RB.STORE_NBR = BF.STORE_NBR)

GROUP BY
	RB.ITEM_NBR,
	BF.FORMATO
	