/*
#'' Consulta para obtener las ventas de cada articulo-tienda
#' 
#' Autor: Eduardo Castro <eduardo.castro0@walmart.com>
#' Colaboracion: Robert Paniagua <mrpania@walmart.com>
#'               Felipe Gerard <felipe.gerard@walmart.com>
#' 
*/

SELECT
	DEPT_NBR,
	CAT_NBR, 
	ITEM_NBR,
	OLD_NBR,
	REPL_GROUP_NBR,
	UPC_NBR,
	ITEM1_DESC,
	TIPO_ART,
	COSTO,
	PRECIO,
	PRECIO_IVA,
	FORMATO,
	SUM(POS_QTY) AS POS_QTY,
	SUM(POS_SALES) AS POS_SALES
FROM
(
	SELECT
		T1.ACCTG_DEPT_NBR AS DEPT_NBR,
		SUBSTR (T1.FINELINE_NBR,3,2) AS CAT_NBR,
		T1.ITEM_NBR,
		T1.OLD_NBR,
		T1.REPL_GROUP_NBR,
		T1.UPC_NBR,
		T1.ITEM1_DESC,
		T1.ITEM_TYPE_CODE AS TIPO_ART,
		T1.VNPK_COST_AMT/T1.VNPK_QTY AS COSTO,
		T1.BASE_UNIT_RTL_AMT AS PRECIO,
		T1.CUST_BASE_RTL_AMT AS PRECIO_IVA,
		CASE WHEN T4.TRAIT_NBR = 9 THEN 'BODEGA' 
		WHEN T4.TRAIT_NBR = 1312 THEN 'MIBODEGA' 
		WHEN T4.TRAIT_NBR IN (969,136) THEN 'BAE' 
		WHEN T4.TRAIT_NBR = 297 THEN 'SUPERCENTER' 
		WHEN T4.TRAIT_NBR = 11 THEN 'SUPERAMA'  
		ELSE 'OTRO' END AS FORMATO,
		T3.WM_YR_WK,
		WHSE_ALIGN_TYPE_CD AS WHSE_ALIGN,
		SUM(T3.SAT_QTY*T5.SAT_MULT + T3.SUN_QTY*T5.SUN_MULT + T3.MON_QTY*T5.MON_MULT + T3.TUE_QTY*T5.TUE_MULT + T3.WED_QTY*T5.WED_MULT + T3.THU_QTY*T5.THU_MULT + T3.FRI_QTY*T5.FRI_MULT) AS POS_QTY,
		SUM(T3.SAT_SALES_AMT*T5.SAT_MULT + T3.SUN_SALES_AMT*T5.SUN_MULT + T3.MON_SALES_AMT*T5.MON_MULT + T3.TUE_SALES_AMT*T5.TUE_MULT + T3.WED_SALES_AMT*T5.WED_MULT + T3.THU_SALES_AMT*T5.THU_MULT + T3.FRI_SALES_AMT*T5.FRI_MULT) AS POS_SALES

	FROM
		MX_CF_VM.item T1,
		MX_CF_VM.Store_info T2,
		MX_CF_VM.Sku_Dly_Pos T3,
		MX_CF_VM.TRAIT_STORE T4,
		(
		SELECT
			WM_YR_WK,
			SUM(SUN_MULT) AS SUN_MULT,
			SUM(MON_MULT) AS MON_MULT,
			SUM(TUE_MULT) AS TUE_MULT,
			SUM(WED_MULT) AS WED_MULT,
			SUM(THU_MULT) AS THU_MULT,
			SUM(FRI_MULT) AS FRI_MULT,
			SUM(SAT_MULT) AS SAT_MULT
		FROM
			MX_CF_VM.CALENDAR_DAY
		WHERE
			GREGORIAN_DATE IN (SELECT GREGORIAN_DATE FROM calendar_day WHERE EXTRACT (YEAR FROM DATE) = EXTRACT (YEAR FROM GREGORIAN_DATE) AND EXTRACT (MONTH FROM DATE) = EXTRACT (MONTH FROM GREGORIAN_DATE))
		GROUP BY 1) T5
	WHERE
		T1.ITEM_NBR =T3.ITEM_NBR
		AND T2.STORE_NBR = T3.STORE_NBR
		AND T2.STORE_NBR = T4.STORE_NBR
		AND T4.TRAIT_NBR IN (11,297,1312,969,136,9) 
		AND T3.WM_YR_WK = T5.WM_YR_WK
		AND T1.VENDOR_NBR NOT IN (18)
	GROUP BY
		1,2,3,4,5,6,7,8,9,10,11,12,13,14
	) AS A
	GROUP BY 
		1,2,3,4,5,6,7,8,9,10,11,12
